image_dir:  "/path/to/train/images_processed"           # folder of processed 2-bands images
mask_dir: "/path/to/labels"                             # /path/to/masks
val_image_dir: "/path/to/val/images_processed"          # validation image 
val_mask_dir: "/path/to/val/labels"                     # validation labels
save_path: "/path/to/output_dir"                        # model saved dir
device: "cuda:0"


lr: 0.001
n_epochs: 100
batch_size: 8 
save_every: 50  # every # epochs